
title: My first GitHub Page
date: 2021-01-11
author: Cesar Sanchez
email: cesarasa@ttu.edu
description: > # this means to ignore newlines until "baseurl:"
  This is my first GitHub Page, I will be learning about this soon!

# social links
twitter_username: pataconcomegato # DO NOT include the @ character, or else the build will fail!
github_username:  CesarAugusto14 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
